### PR TITLE
Port to 1.19.3

### PR DESCRIPTION
**Pull request by Treetrain1**
Enables Eden Ring to be ran on 1.19.3.

Worldgen features are now registered via data packs, so features have been converted to use datagen.
A new gradle task, `runDatagenClient` has been added to trigger datagen in order to refresh worldgen.

Biomes are now built differently to be consistent with other BetterX mods.

### CODE REVIEW

**Comment by Treetrain1** [comment]
Are there any problems or complaints with this PR?

**Comment by paulevsGitch** [comment]
No, everything is fine, it will be merged later when I will have enough time

**Comment by paulevsGitch** [comment]
I want to fix some issues in 1.19.2 version and publish it before merging

**Comment by OpenBagTwo** [comment]
@Treetrain1 Wondering if you've looked at all into updating your port to 1.19.4 / 1.20 (BCLib 3). If you haven't, I might give it a shot.

**Comment by Treetrain1** [comment]
> @Treetrain1 Wondering if you've looked at all into updating your port to 1.19.4 / 1.20 (BCLib 3). If you haven't, I might give it a shot.

I haven't looked at updating my port. I'm fine with you porting this to 1.20. I'll just close this PR.

**Pull request closed without merging**
