### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by EndsM**
The localization for book are not ready yet.
By the way, I saw a mod using bulk or something to auto sync keys in different localization files, fill the untranslate keys with original english translation. Would there be a possible to use that in here too? That would help for translators to keep formation and better track what have changed.
Though it still OK for now, the books seems have some trouble to show the symbols in chinese environment btw.

### CODE REVIEW

**Comment by paulevsGitch** [comment]
> By the way, I saw a mod using bulk or something to auto sync keys in different localization files, fill the untranslate keys with original english translation

Technically it is possible, but this will require each book page have unique ID (to find matches) as the pages can be added both before and after already existing content. Another thing is that pages are constructed directly from translation Json, so probably some translations require more pages for same text and this can cause conflicts with this system

**Comment by EndsM** [comment]
I see, so I checked the stroage method for books' localization again.
It seems each subject are stored in individual chuncks, and the content are stored serialized. though the each entries are not marked in any means. It may still able to write a program to help create the book and manage the localizations.
I actually leaning ASP.Net and may have some ideas about this, but I think is not likely I can make that any soon... But it would be a helpful tool for patchouli mod.
But before that, I still think we can automanage the localization for main translation file, but keep the books' as it.

**Comment by paulevsGitch** [comment]
Yes, the main file can be easily automated as it is just a pair of key-name entries and the key order is not important

**Comment by EndsM** [comment]
That's great, and I think I will work on import a json file created by Patchouli first.
Have a nice day, is about midnight here, so I will go for now.

**Pull request merged**
